<MyW>:
	ActionBar:
		pos_hint: {'top': 1}
		ActionView:
			use_separator: True
			ActionPrevious:
				title:'Action Bar'
				with_previous: False
			ActionOverflow:
			ActionButton:
				text: 'Btn0'
				icon: 'floppy.png'
			ActionButton:
				text: 'Btn1'
			ActionButton:
				text: 'Btn2'
			ActionButton:
				text: 'Btn3'
			ActionButton:
				text: 'Btn4'
			ActionGroup:
				text: 'Group1'
				ActionButton:
					text: 'Btn5'
				ActionButton:
					text: 'Btn6'
				ActionButton:
					text: 'Btn7'
<MyW1>:
	Button:
		id: label1
		size_hint: 0.2, 0.2
		pos_hint:{'center_x':0.5, 'center_y':0.5}
		text: 'B1'
	Button:
		id: label2
		size_hint: 0.1, 0.1
		pos_hint:{'center_x':0.1, 'center_y':0.1}
		text: 'B2'
